# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sumedh/kfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sumedh/kfs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sumedh/kfs/CMakeFiles /home/sumedh/kfs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sumedh/kfs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Version.cc

# Build rule for target.
Version.cc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Version.cc
.PHONY : Version.cc

# fast build rule for target.
Version.cc/fast:
	$(MAKE) -f src/cc/common/CMakeFiles/Version.cc.dir/build.make src/cc/common/CMakeFiles/Version.cc.dir/build
.PHONY : Version.cc/fast

#=============================================================================
# Target rules for targets named kfsCommon

# Build rule for target.
kfsCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsCommon
.PHONY : kfsCommon

# fast build rule for target.
kfsCommon/fast:
	$(MAKE) -f src/cc/common/CMakeFiles/kfsCommon.dir/build.make src/cc/common/CMakeFiles/kfsCommon.dir/build
.PHONY : kfsCommon/fast

#=============================================================================
# Target rules for targets named kfsCommon-shared

# Build rule for target.
kfsCommon-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsCommon-shared
.PHONY : kfsCommon-shared

# fast build rule for target.
kfsCommon-shared/fast:
	$(MAKE) -f src/cc/common/CMakeFiles/kfsCommon-shared.dir/build.make src/cc/common/CMakeFiles/kfsCommon-shared.dir/build
.PHONY : kfsCommon-shared/fast

#=============================================================================
# Target rules for targets named rebalancer

# Build rule for target.
rebalancer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebalancer
.PHONY : rebalancer

# fast build rule for target.
rebalancer/fast:
	$(MAKE) -f src/cc/rebalancer/CMakeFiles/rebalancer.dir/build.make src/cc/rebalancer/CMakeFiles/rebalancer.dir/build
.PHONY : rebalancer/fast

#=============================================================================
# Target rules for targets named filelister

# Build rule for target.
filelister: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filelister
.PHONY : filelister

# fast build rule for target.
filelister/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/filelister.dir/build.make src/cc/meta/CMakeFiles/filelister.dir/build
.PHONY : filelister/fast

#=============================================================================
# Target rules for targets named kfsMeta

# Build rule for target.
kfsMeta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsMeta
.PHONY : kfsMeta

# fast build rule for target.
kfsMeta/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/kfsMeta.dir/build.make src/cc/meta/CMakeFiles/kfsMeta.dir/build
.PHONY : kfsMeta/fast

#=============================================================================
# Target rules for targets named kfsMeta-shared

# Build rule for target.
kfsMeta-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsMeta-shared
.PHONY : kfsMeta-shared

# fast build rule for target.
kfsMeta-shared/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/kfsMeta-shared.dir/build.make src/cc/meta/CMakeFiles/kfsMeta-shared.dir/build
.PHONY : kfsMeta-shared/fast

#=============================================================================
# Target rules for targets named kfsfsck

# Build rule for target.
kfsfsck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsfsck
.PHONY : kfsfsck

# fast build rule for target.
kfsfsck/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/kfsfsck.dir/build.make src/cc/meta/CMakeFiles/kfsfsck.dir/build
.PHONY : kfsfsck/fast

#=============================================================================
# Target rules for targets named logcompactor

# Build rule for target.
logcompactor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logcompactor
.PHONY : logcompactor

# fast build rule for target.
logcompactor/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/logcompactor.dir/build.make src/cc/meta/CMakeFiles/logcompactor.dir/build
.PHONY : logcompactor/fast

#=============================================================================
# Target rules for targets named metaserver

# Build rule for target.
metaserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metaserver
.PHONY : metaserver

# fast build rule for target.
metaserver/fast:
	$(MAKE) -f src/cc/meta/CMakeFiles/metaserver.dir/build.make src/cc/meta/CMakeFiles/metaserver.dir/build
.PHONY : metaserver/fast

#=============================================================================
# Target rules for targets named chunkscrubber

# Build rule for target.
chunkscrubber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chunkscrubber
.PHONY : chunkscrubber

# fast build rule for target.
chunkscrubber/fast:
	$(MAKE) -f src/cc/chunk/CMakeFiles/chunkscrubber.dir/build.make src/cc/chunk/CMakeFiles/chunkscrubber.dir/build
.PHONY : chunkscrubber/fast

#=============================================================================
# Target rules for targets named chunkserver

# Build rule for target.
chunkserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chunkserver
.PHONY : chunkserver

# fast build rule for target.
chunkserver/fast:
	$(MAKE) -f src/cc/chunk/CMakeFiles/chunkserver.dir/build.make src/cc/chunk/CMakeFiles/chunkserver.dir/build
.PHONY : chunkserver/fast

#=============================================================================
# Target rules for targets named chunktrimmer

# Build rule for target.
chunktrimmer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chunktrimmer
.PHONY : chunktrimmer

# fast build rule for target.
chunktrimmer/fast:
	$(MAKE) -f src/cc/chunk/CMakeFiles/chunktrimmer.dir/build.make src/cc/chunk/CMakeFiles/chunktrimmer.dir/build
.PHONY : chunktrimmer/fast

#=============================================================================
# Target rules for targets named kfsClient

# Build rule for target.
kfsClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsClient
.PHONY : kfsClient

# fast build rule for target.
kfsClient/fast:
	$(MAKE) -f src/cc/libkfsClient/CMakeFiles/kfsClient.dir/build.make src/cc/libkfsClient/CMakeFiles/kfsClient.dir/build
.PHONY : kfsClient/fast

#=============================================================================
# Target rules for targets named kfsClient-shared

# Build rule for target.
kfsClient-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsClient-shared
.PHONY : kfsClient-shared

# fast build rule for target.
kfsClient-shared/fast:
	$(MAKE) -f src/cc/libkfsClient/CMakeFiles/kfsClient-shared.dir/build.make src/cc/libkfsClient/CMakeFiles/kfsClient-shared.dir/build
.PHONY : kfsClient-shared/fast

#=============================================================================
# Target rules for targets named kfsIO

# Build rule for target.
kfsIO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsIO
.PHONY : kfsIO

# fast build rule for target.
kfsIO/fast:
	$(MAKE) -f src/cc/libkfsIO/CMakeFiles/kfsIO.dir/build.make src/cc/libkfsIO/CMakeFiles/kfsIO.dir/build
.PHONY : kfsIO/fast

#=============================================================================
# Target rules for targets named kfsIO-shared

# Build rule for target.
kfsIO-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsIO-shared
.PHONY : kfsIO-shared

# fast build rule for target.
kfsIO-shared/fast:
	$(MAKE) -f src/cc/libkfsIO/CMakeFiles/kfsIO-shared.dir/build.make src/cc/libkfsIO/CMakeFiles/kfsIO-shared.dir/build
.PHONY : kfsIO-shared/fast

#=============================================================================
# Target rules for targets named cpfromkfs

# Build rule for target.
cpfromkfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpfromkfs
.PHONY : cpfromkfs

# fast build rule for target.
cpfromkfs/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/cpfromkfs.dir/build.make src/cc/tools/CMakeFiles/cpfromkfs.dir/build
.PHONY : cpfromkfs/fast

#=============================================================================
# Target rules for targets named cptokfs

# Build rule for target.
cptokfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cptokfs
.PHONY : cptokfs

# fast build rule for target.
cptokfs/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/cptokfs.dir/build.make src/cc/tools/CMakeFiles/cptokfs.dir/build
.PHONY : cptokfs/fast

#=============================================================================
# Target rules for targets named kfscp

# Build rule for target.
kfscp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfscp
.PHONY : kfscp

# fast build rule for target.
kfscp/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfscp.dir/build.make src/cc/tools/CMakeFiles/kfscp.dir/build
.PHONY : kfscp/fast

#=============================================================================
# Target rules for targets named kfsdataverify

# Build rule for target.
kfsdataverify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsdataverify
.PHONY : kfsdataverify

# fast build rule for target.
kfsdataverify/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsdataverify.dir/build.make src/cc/tools/CMakeFiles/kfsdataverify.dir/build
.PHONY : kfsdataverify/fast

#=============================================================================
# Target rules for targets named kfsfileenum

# Build rule for target.
kfsfileenum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsfileenum
.PHONY : kfsfileenum

# fast build rule for target.
kfsfileenum/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsfileenum.dir/build.make src/cc/tools/CMakeFiles/kfsfileenum.dir/build
.PHONY : kfsfileenum/fast

#=============================================================================
# Target rules for targets named kfsls

# Build rule for target.
kfsls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsls
.PHONY : kfsls

# fast build rule for target.
kfsls/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsls.dir/build.make src/cc/tools/CMakeFiles/kfsls.dir/build
.PHONY : kfsls/fast

#=============================================================================
# Target rules for targets named kfsping

# Build rule for target.
kfsping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsping
.PHONY : kfsping

# fast build rule for target.
kfsping/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsping.dir/build.make src/cc/tools/CMakeFiles/kfsping.dir/build
.PHONY : kfsping/fast

#=============================================================================
# Target rules for targets named kfsput

# Build rule for target.
kfsput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsput
.PHONY : kfsput

# fast build rule for target.
kfsput/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsput.dir/build.make src/cc/tools/CMakeFiles/kfsput.dir/build
.PHONY : kfsput/fast

#=============================================================================
# Target rules for targets named kfsretire

# Build rule for target.
kfsretire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsretire
.PHONY : kfsretire

# fast build rule for target.
kfsretire/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsretire.dir/build.make src/cc/tools/CMakeFiles/kfsretire.dir/build
.PHONY : kfsretire/fast

#=============================================================================
# Target rules for targets named kfsshell

# Build rule for target.
kfsshell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsshell
.PHONY : kfsshell

# fast build rule for target.
kfsshell/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsshell.dir/build.make src/cc/tools/CMakeFiles/kfsshell.dir/build
.PHONY : kfsshell/fast

#=============================================================================
# Target rules for targets named kfsstats

# Build rule for target.
kfsstats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsstats
.PHONY : kfsstats

# fast build rule for target.
kfsstats/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfsstats.dir/build.make src/cc/tools/CMakeFiles/kfsstats.dir/build
.PHONY : kfsstats/fast

#=============================================================================
# Target rules for targets named kfstoggleworm

# Build rule for target.
kfstoggleworm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfstoggleworm
.PHONY : kfstoggleworm

# fast build rule for target.
kfstoggleworm/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/kfstoggleworm.dir/build.make src/cc/tools/CMakeFiles/kfstoggleworm.dir/build
.PHONY : kfstoggleworm/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/tools.dir/build.make src/cc/tools/CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named tools-shared

# Build rule for target.
tools-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools-shared
.PHONY : tools-shared

# fast build rule for target.
tools-shared/fast:
	$(MAKE) -f src/cc/tools/CMakeFiles/tools-shared.dir/build.make src/cc/tools/CMakeFiles/tools-shared.dir/build
.PHONY : tools-shared/fast

#=============================================================================
# Target rules for targets named KfsDataGen

# Build rule for target.
KfsDataGen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsDataGen
.PHONY : KfsDataGen

# fast build rule for target.
KfsDataGen/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsDataGen.dir/build.make src/cc/tests/CMakeFiles/KfsDataGen.dir/build
.PHONY : KfsDataGen/fast

#=============================================================================
# Target rules for targets named KfsDirFileTester

# Build rule for target.
KfsDirFileTester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsDirFileTester
.PHONY : KfsDirFileTester

# fast build rule for target.
KfsDirFileTester/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsDirFileTester.dir/build.make src/cc/tests/CMakeFiles/KfsDirFileTester.dir/build
.PHONY : KfsDirFileTester/fast

#=============================================================================
# Target rules for targets named KfsDirScanTest

# Build rule for target.
KfsDirScanTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsDirScanTest
.PHONY : KfsDirScanTest

# fast build rule for target.
KfsDirScanTest/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsDirScanTest.dir/build.make src/cc/tests/CMakeFiles/KfsDirScanTest.dir/build
.PHONY : KfsDirScanTest/fast

#=============================================================================
# Target rules for targets named KfsLogTest

# Build rule for target.
KfsLogTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsLogTest
.PHONY : KfsLogTest

# fast build rule for target.
KfsLogTest/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsLogTest.dir/build.make src/cc/tests/CMakeFiles/KfsLogTest.dir/build
.PHONY : KfsLogTest/fast

#=============================================================================
# Target rules for targets named KfsPerfReader

# Build rule for target.
KfsPerfReader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsPerfReader
.PHONY : KfsPerfReader

# fast build rule for target.
KfsPerfReader/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsPerfReader.dir/build.make src/cc/tests/CMakeFiles/KfsPerfReader.dir/build
.PHONY : KfsPerfReader/fast

#=============================================================================
# Target rules for targets named KfsPerfWriter

# Build rule for target.
KfsPerfWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsPerfWriter
.PHONY : KfsPerfWriter

# fast build rule for target.
KfsPerfWriter/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsPerfWriter.dir/build.make src/cc/tests/CMakeFiles/KfsPerfWriter.dir/build
.PHONY : KfsPerfWriter/fast

#=============================================================================
# Target rules for targets named KfsRW

# Build rule for target.
KfsRW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsRW
.PHONY : KfsRW

# fast build rule for target.
KfsRW/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsRW.dir/build.make src/cc/tests/CMakeFiles/KfsRW.dir/build
.PHONY : KfsRW/fast

#=============================================================================
# Target rules for targets named KfsReader

# Build rule for target.
KfsReader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsReader
.PHONY : KfsReader

# fast build rule for target.
KfsReader/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsReader.dir/build.make src/cc/tests/CMakeFiles/KfsReader.dir/build
.PHONY : KfsReader/fast

#=============================================================================
# Target rules for targets named KfsRecordAppend

# Build rule for target.
KfsRecordAppend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsRecordAppend
.PHONY : KfsRecordAppend

# fast build rule for target.
KfsRecordAppend/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsRecordAppend.dir/build.make src/cc/tests/CMakeFiles/KfsRecordAppend.dir/build
.PHONY : KfsRecordAppend/fast

#=============================================================================
# Target rules for targets named KfsSeekWrite

# Build rule for target.
KfsSeekWrite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsSeekWrite
.PHONY : KfsSeekWrite

# fast build rule for target.
KfsSeekWrite/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsSeekWrite.dir/build.make src/cc/tests/CMakeFiles/KfsSeekWrite.dir/build
.PHONY : KfsSeekWrite/fast

#=============================================================================
# Target rules for targets named KfsTrunc

# Build rule for target.
KfsTrunc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsTrunc
.PHONY : KfsTrunc

# fast build rule for target.
KfsTrunc/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsTrunc.dir/build.make src/cc/tests/CMakeFiles/KfsTrunc.dir/build
.PHONY : KfsTrunc/fast

#=============================================================================
# Target rules for targets named KfsWriter

# Build rule for target.
KfsWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KfsWriter
.PHONY : KfsWriter

# fast build rule for target.
KfsWriter/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/KfsWriter.dir/build.make src/cc/tests/CMakeFiles/KfsWriter.dir/build
.PHONY : KfsWriter/fast

#=============================================================================
# Target rules for targets named mkfstree

# Build rule for target.
mkfstree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkfstree
.PHONY : mkfstree

# fast build rule for target.
mkfstree/fast:
	$(MAKE) -f src/cc/tests/CMakeFiles/mkfstree.dir/build.make src/cc/tests/CMakeFiles/mkfstree.dir/build
.PHONY : mkfstree/fast

#=============================================================================
# Target rules for targets named kfsEmulator

# Build rule for target.
kfsEmulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsEmulator
.PHONY : kfsEmulator

# fast build rule for target.
kfsEmulator/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/kfsEmulator.dir/build.make src/cc/emulator/CMakeFiles/kfsEmulator.dir/build
.PHONY : kfsEmulator/fast

#=============================================================================
# Target rules for targets named kfsEmulator-shared

# Build rule for target.
kfsEmulator-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfsEmulator-shared
.PHONY : kfsEmulator-shared

# fast build rule for target.
kfsEmulator-shared/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/kfsEmulator-shared.dir/build.make src/cc/emulator/CMakeFiles/kfsEmulator-shared.dir/build
.PHONY : kfsEmulator-shared/fast

#=============================================================================
# Target rules for targets named rebalanceexecutor

# Build rule for target.
rebalanceexecutor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebalanceexecutor
.PHONY : rebalanceexecutor

# fast build rule for target.
rebalanceexecutor/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/rebalanceexecutor.dir/build.make src/cc/emulator/CMakeFiles/rebalanceexecutor.dir/build
.PHONY : rebalanceexecutor/fast

#=============================================================================
# Target rules for targets named rebalanceplanner

# Build rule for target.
rebalanceplanner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rebalanceplanner
.PHONY : rebalanceplanner

# fast build rule for target.
rebalanceplanner/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/rebalanceplanner.dir/build.make src/cc/emulator/CMakeFiles/rebalanceplanner.dir/build
.PHONY : rebalanceplanner/fast

#=============================================================================
# Target rules for targets named replicachecker

# Build rule for target.
replicachecker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 replicachecker
.PHONY : replicachecker

# fast build rule for target.
replicachecker/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/replicachecker.dir/build.make src/cc/emulator/CMakeFiles/replicachecker.dir/build
.PHONY : replicachecker/fast

#=============================================================================
# Target rules for targets named rereplicator

# Build rule for target.
rereplicator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rereplicator
.PHONY : rereplicator

# fast build rule for target.
rereplicator/fast:
	$(MAKE) -f src/cc/emulator/CMakeFiles/rereplicator.dir/build.make src/cc/emulator/CMakeFiles/rereplicator.dir/build
.PHONY : rereplicator/fast

#=============================================================================
# Target rules for targets named telemetry_repeater

# Build rule for target.
telemetry_repeater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 telemetry_repeater
.PHONY : telemetry_repeater

# fast build rule for target.
telemetry_repeater/fast:
	$(MAKE) -f src/cc/telemetry/CMakeFiles/telemetry_repeater.dir/build.make src/cc/telemetry/CMakeFiles/telemetry_repeater.dir/build
.PHONY : telemetry_repeater/fast

#=============================================================================
# Target rules for targets named telemetry_server

# Build rule for target.
telemetry_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 telemetry_server
.PHONY : telemetry_server

# fast build rule for target.
telemetry_server/fast:
	$(MAKE) -f src/cc/telemetry/CMakeFiles/telemetry_server.dir/build.make src/cc/telemetry/CMakeFiles/telemetry_server.dir/build
.PHONY : telemetry_server/fast

#=============================================================================
# Target rules for targets named qcdio

# Build rule for target.
qcdio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qcdio
.PHONY : qcdio

# fast build rule for target.
qcdio/fast:
	$(MAKE) -f src/cc/qcdio/CMakeFiles/qcdio.dir/build.make src/cc/qcdio/CMakeFiles/qcdio.dir/build
.PHONY : qcdio/fast

#=============================================================================
# Target rules for targets named qcdio-shared

# Build rule for target.
qcdio-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qcdio-shared
.PHONY : qcdio-shared

# fast build rule for target.
qcdio-shared/fast:
	$(MAKE) -f src/cc/qcdio/CMakeFiles/qcdio-shared.dir/build.make src/cc/qcdio/CMakeFiles/qcdio-shared.dir/build
.PHONY : qcdio-shared/fast

#=============================================================================
# Target rules for targets named kfs_access

# Build rule for target.
kfs_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kfs_access
.PHONY : kfs_access

# fast build rule for target.
kfs_access/fast:
	$(MAKE) -f src/cc/access/CMakeFiles/kfs_access.dir/build.make src/cc/access/CMakeFiles/kfs_access.dir/build
.PHONY : kfs_access/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Version.cc"
	@echo "... kfsCommon"
	@echo "... kfsCommon-shared"
	@echo "... rebalancer"
	@echo "... filelister"
	@echo "... kfsMeta"
	@echo "... kfsMeta-shared"
	@echo "... kfsfsck"
	@echo "... logcompactor"
	@echo "... metaserver"
	@echo "... chunkscrubber"
	@echo "... chunkserver"
	@echo "... chunktrimmer"
	@echo "... kfsClient"
	@echo "... kfsClient-shared"
	@echo "... kfsIO"
	@echo "... kfsIO-shared"
	@echo "... cpfromkfs"
	@echo "... cptokfs"
	@echo "... kfscp"
	@echo "... kfsdataverify"
	@echo "... kfsfileenum"
	@echo "... kfsls"
	@echo "... kfsping"
	@echo "... kfsput"
	@echo "... kfsretire"
	@echo "... kfsshell"
	@echo "... kfsstats"
	@echo "... kfstoggleworm"
	@echo "... tools"
	@echo "... tools-shared"
	@echo "... KfsDataGen"
	@echo "... KfsDirFileTester"
	@echo "... KfsDirScanTest"
	@echo "... KfsLogTest"
	@echo "... KfsPerfReader"
	@echo "... KfsPerfWriter"
	@echo "... KfsRW"
	@echo "... KfsReader"
	@echo "... KfsRecordAppend"
	@echo "... KfsSeekWrite"
	@echo "... KfsTrunc"
	@echo "... KfsWriter"
	@echo "... mkfstree"
	@echo "... kfsEmulator"
	@echo "... kfsEmulator-shared"
	@echo "... rebalanceexecutor"
	@echo "... rebalanceplanner"
	@echo "... replicachecker"
	@echo "... rereplicator"
	@echo "... telemetry_repeater"
	@echo "... telemetry_server"
	@echo "... qcdio"
	@echo "... qcdio-shared"
	@echo "... kfs_access"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

